-- Cria tabelas para conteúdo da seção "Quem Somos"
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_name = 'about_content'
  ) THEN
    CREATE TABLE public.about_content (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      subtitle TEXT NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    INSERT INTO public.about_content (title, subtitle)
    VALUES (
      'Realizamos projetos socioambientais e ações estratégicas',
      'Nossa missão é promover o desenvolvimento sustentável da maricultura, apoiando nossos associados com conhecimento técnico e científico.'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema = 'public' AND table_name = 'about_features'
  ) THEN
    CREATE TABLE public.about_features (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      icon_key TEXT NOT NULL, -- chave para o ícone (ex: fish, users, waves, award)
      display_order INT NOT NULL DEFAULT 0
    );
    -- Seeds iniciais
    INSERT INTO public.about_features (title, description, icon_key, display_order) VALUES
    ('Desenvolvimento Sustentável', 'Promovemos práticas sustentáveis na maricultura, respeitando o meio ambiente marinho.', 'fish', 0),
    ('Investigação Científica', 'Apoiamos pesquisas e estudos para o avanço da maricultura no estado de São Paulo.', 'users', 1),
    ('Organização da Maricultura', 'Estruturamos e organizamos o setor para melhor atender produtores e consumidores.', 'waves', 2),
    ('Excelência Reconhecida', 'Certificações internacionais e reconhecimento pela qualidade dos nossos serviços.', 'award', 3);
  END IF;

  -- Habilita RLS (opcional) — somente admins salvarão via Service Role
  BEGIN
    EXECUTE 'ALTER TABLE public.about_content ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.about_features ENABLE ROW LEVEL SECURITY';
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;


