-- Cria tabelas para a seção "Maricultura" (mesma estrutura do Quem Somos / about)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'maricultura_content'
  ) THEN
    CREATE TABLE public.maricultura_content (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      subtitle TEXT NOT NULL,
      content JSONB DEFAULT '[]'::jsonb,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    INSERT INTO public.maricultura_content (id, title, subtitle)
    VALUES (
      1,
      'O que é Maricultura',
      'A maricultura é a criação de organismos marinhos em ambiente controlado, contribuindo para a segurança alimentar e o desenvolvimento sustentável do litoral.'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'maricultura_features'
  ) THEN
    CREATE TABLE public.maricultura_features (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      icon_key TEXT NOT NULL,
      display_order INT NOT NULL DEFAULT 0
    );
    INSERT INTO public.maricultura_features (title, description, icon_key, display_order) VALUES
    ('Cultivo Sustentável', 'Práticas que respeitam o ecossistema marinho e a qualidade dos produtos.', 'fish', 0),
    ('Espécies Cultivadas', 'Moluscos, peixes e algas em sistemas adequados ao litoral paulista.', 'waves', 1),
    ('Qualidade e Rastreabilidade', 'Padrões de produção e certificações que garantem a origem e a segurança.', 'award', 2),
    ('Geração de Emprego', 'A maricultura fortalece a economia costeira e as comunidades locais.', 'users', 3);
  END IF;

  -- RLS (admins usam Service Role)
  BEGIN
    EXECUTE 'ALTER TABLE public.maricultura_content ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.maricultura_features ENABLE ROW LEVEL SECURITY';
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;

COMMENT ON TABLE public.maricultura_content IS 'Conteúdo editável da seção Maricultura na Home (título, subtítulo, blocos do page builder)';
COMMENT ON TABLE public.maricultura_features IS 'Cards da seção Maricultura (título, descrição, ícone, ordem)';
