-- Cria tabelas para a seção "Turismo" (mesmo padrão de Maricultura / Quem Somos)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'turismo_content'
  ) THEN
    CREATE TABLE public.turismo_content (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      subtitle TEXT NOT NULL,
      content JSONB DEFAULT '[]'::jsonb,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    INSERT INTO public.turismo_content (id, title, subtitle)
    VALUES (
      1,
      'Turismo no Litoral',
      'Conheça as belezas e oportunidades de turismo na região da maricultura no litoral norte de São Paulo.'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'turismo_features'
  ) THEN
    CREATE TABLE public.turismo_features (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      icon_key TEXT NOT NULL,
      display_order INT NOT NULL DEFAULT 0
    );
    INSERT INTO public.turismo_features (title, description, icon_key, display_order) VALUES
    ('Praias e Natureza', 'Litoral preservado com praias, trilhas e paisagens que encantam visitantes.', 'waves', 0),
    ('Gastronomia', 'Experiências gastronômicas com frutos do mar e culinária local.', 'fish', 1),
    ('Roteiros e Visitas', 'Conheça fazendas de maricultura e a rotina dos produtores.', 'mapPin', 2),
    ('Eventos e Festivais', 'Eventos que unem turismo, cultura e maricultura na região.', 'calendar', 3);
  END IF;

  BEGIN
    EXECUTE 'ALTER TABLE public.turismo_content ENABLE ROW LEVEL SECURITY';
    EXECUTE 'ALTER TABLE public.turismo_features ENABLE ROW LEVEL SECURITY';
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;

COMMENT ON TABLE public.turismo_content IS 'Conteúdo editável da seção Turismo na Home (título, subtítulo, blocos do page builder)';
COMMENT ON TABLE public.turismo_features IS 'Cards da seção Turismo (título, descrição, ícone, ordem)';
